-- Link Messenger Database Migration for Supabase SQL Editor
-- Run this in your Supabase Dashboard -> SQL Editor (https://supabase.com/dashboard/project/dvyvcqztgmkklswbuqje/sql)

-- 1. Create link_users table
CREATE TABLE IF NOT EXISTS public.link_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    avatar TEXT DEFAULT '⚡',
    status TEXT DEFAULT 'Hey there! I am using Link.',
    online INT DEFAULT 1,
    last_seen TEXT DEFAULT 'Just now'
);

-- 2. Create link_chats table
CREATE TABLE IF NOT EXISTS public.link_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id TEXT UNIQUE NOT NULL,
    type TEXT DEFAULT 'direct',
    name TEXT NOT NULL,
    participants TEXT NOT NULL,
    last_message TEXT DEFAULT 'Chat started',
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create link_messages table
CREATE TABLE IF NOT EXISTS public.link_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id TEXT NOT NULL,
    sender_id TEXT NOT NULL,
    sender_name TEXT NOT NULL,
    content TEXT NOT NULL,
    attachment TEXT,
    reaction TEXT,
    timestamp TEXT DEFAULT CURRENT_TIMESTAMP
);

-- 4. Create link_statuses table
CREATE TABLE IF NOT EXISTS public.link_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    user_name TEXT NOT NULL,
    user_avatar TEXT DEFAULT '⚡',
    content TEXT NOT NULL,
    bg_gradient TEXT DEFAULT '#6366f1',
    media_url TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    expires_at TEXT NOT NULL,
    likes INT DEFAULT 0
);

-- 5. Create link_status_views table
CREATE TABLE IF NOT EXISTS public.link_status_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_id INT NOT NULL,
    viewer_id TEXT NOT NULL,
    viewed_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS and add public access policies
ALTER TABLE public.link_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.link_chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.link_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.link_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.link_status_views ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public link_users policy" ON public.link_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public link_chats policy" ON public.link_chats FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public link_messages policy" ON public.link_messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public link_statuses policy" ON public.link_statuses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public link_status_views policy" ON public.link_status_views FOR ALL USING (true) WITH CHECK (true);

-- Seed initial data
INSERT INTO public.link_users (user_id, name, avatar, status, online, last_seen) VALUES
('admin', 'System Administrator', '⚡', 'Available for support', 1, 'Just now'),
('teacher', 'Demo Teacher', '📚', 'In class', 1, '2m ago'),
('student', 'Demo Student', '🎓', 'Studying Math', 0, '15m ago'),
('alex_m', 'Alex Morgan', '🚀', 'Building Link Messenger!', 1, 'Just now'),
('sarah_j', 'Sarah Jenkins', '🎨', 'Designing UI', 1, '5m ago')
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO public.link_chats (chat_id, type, name, participants, last_message, updated_at) VALUES
('chat_announcements', 'group', '📢 Campus Announcements', 'admin,teacher,student,alex_m,sarah_j', 'Welcome to Link Messenger!', NOW())
ON CONFLICT (chat_id) DO NOTHING;

INSERT INTO public.link_messages (chat_id, sender_id, sender_name, content, timestamp) VALUES
('chat_announcements', 'admin', 'System Administrator', 'Welcome to Link Messenger on Supabase! 🎉', NOW());
